/**
 * ARCHETYPE C — NO GROUND TRUTH.  Hypothesised account: Spinny.
 *
 * What is the right price for this car? The question has no answer. There is
 * only what happened at the price you actually set, and no observation
 * whatsoever of what would have happened at any other. No label exists to
 * grade against, now or ever.
 *
 * So the evaluation is not grading, it is OFF-POLICY EVALUATION: estimating
 * what a new pricing policy would have earned, using a log generated by the old
 * one. Three estimators, and the differences between them matter:
 *
 *   DIRECT METHOD   fit a demand model on the log, simulate the new policy
 *                   through it. Low variance, and inherits every bias of the
 *                   fitted model. It will confidently rate a policy that only
 *                   prices where the log is thin.
 *
 *   IPS             reweight each logged outcome by how much more likely the
 *                   new policy was to take that action. Unbiased, and its
 *                   variance explodes when the two policies disagree.
 *
 *   DOUBLY ROBUST   the direct estimate plus IPS-weighted residuals. Correct if
 *                   EITHER the demand model or the propensities are right.
 *
 * And the finding that actually matters commercially:
 *
 *   ALL THREE REQUIRE THAT THE OLD POLICY EXPLORED.
 *
 * If yesterday's pricing was deterministic — a fixed markup on a valuation,
 * which is what most desks run — then every propensity is 1 or 0, no reweighting
 * is possible, and the historical data cannot evaluate any new policy at all.
 * The company owns four years of pricing history and none of it can answer the
 * question it wants answered. That is usually discovered after the model is
 * built. The run below demonstrates it by replaying the same evaluation against
 * an exploring log and a deterministic one.
 */

import type { Adapter } from '../../types.ts';
import type { Scenario, ScenarioResult, RunOpts } from '../types.ts';
import { rng } from '../../core/stats.ts';
import { Cache } from '../../core/cache.ts';
import { callModel } from '../call.ts';

const MAKES = ['Maruti Swift','Hyundai i20','Honda City','Maruti Baleno','Tata Nexon',
  'Hyundai Creta','Maruti Wagon R','Toyota Innova','Kia Seltos','Renault Kwid'];
const CITIES = ['Delhi NCR','Bengaluru','Pune','Hyderabad','Chennai','Mumbai'];

/** Price levels as multipliers on a reference valuation. Discrete so propensities exist. */
const LEVELS = [0.88, 0.92, 0.96, 1.00, 1.04, 1.08, 1.12];
const HOLD_COST_PER_DAY = 420;      // parking, capital, reconditioning drag
const WINDOW_DAYS = 30;

type Car = {
  id: string; text: string;
  acquisition: number;     // what the platform paid
  reference: number;       // internal valuation, noisy
  trueValue: number;       // latent market clearing value, never observed
};

function build(n: number, seed: number): Car[] {
  const r = rng(seed), out: Car[] = [];
  for (let i = 0; i < n; i++) {
    const make = MAKES[Math.floor(r()*MAKES.length)]!;
    const year = 2016 + Math.floor(r()*9);
    const km = Math.round((10 + r()*110) * 1000);
    const owners = 1 + Math.floor(r()*3);
    const city = CITIES[Math.floor(r()*CITIES.length)]!;
    const service = r() < 0.6 ? 'full service history' : 'partial records';
    const cond = ['minor scratches','repainted bumper','excellent','tyres due','AC service due'][Math.floor(r()*5)]!;

    const base = 250_000 + (year-2016)*55_000 + (r()-0.5)*90_000;
    const trueValue = Math.max(120_000, base - km*0.9 - (owners-1)*28_000 + (service.startsWith('full')?18_000:0));
    out.push({
      id: `car-${String(i).padStart(4,'0')}`,
      acquisition: Math.round(trueValue * (0.86 + r()*0.06)),
      reference:   Math.round(trueValue * (0.97 + (r()-0.5)*0.12)),   // valuation is noisy
      trueValue:   Math.round(trueValue),
      text: `${year} ${make}, ${km.toLocaleString('en-IN')} km, ${owners} owner${owners>1?'s':''}, ${city}. ${service}. Condition: ${cond}.`,
    });
  }
  return out;
}

/** Probability of selling inside the window at a given price. */
function pSell(price: number, trueValue: number): number {
  const gap = (trueValue - price) / trueValue;
  return 1 / (1 + Math.exp(-(gap * 14 + 0.35)));
}

function reward(price: number, car: Car, sold: boolean, r: () => number): number {
  if (!sold) return -HOLD_COST_PER_DAY * WINDOW_DAYS;         // still on the lot
  const days = 3 + Math.floor(r() * WINDOW_DAYS);
  return price - car.acquisition - HOLD_COST_PER_DAY * days;
}

/** Logging policy: softmax over levels. temp 0 is the deterministic desk. */
function logPropensities(car: Car, temp: number): number[] {
  const target = car.reference * 1.02;
  const util = LEVELS.map(L => -Math.abs(car.reference * L - target) / car.reference);
  if (temp <= 0) {
    const best = util.indexOf(Math.max(...util));
    return util.map((_, i) => i === best ? 1 : 0);
  }
  const ex = util.map(u => Math.exp(u / temp));
  const s = ex.reduce((a,b) => a+b, 0);
  return ex.map(e => e/s);
}

function sample(ps: number[], r: () => number): number {
  let acc = 0, x = r();
  for (let i = 0; i < ps.length; i++) { acc += ps[i]!; if (x <= acc) return i; }
  return ps.length - 1;
}

type LogRow = { car: Car; action: number; propensity: number; sold: boolean; reward: number };

function makeLog(cars: Car[], temp: number, seed: number): LogRow[] {
  const r = rng(seed);
  return cars.map(car => {
    const ps = logPropensities(car, temp);
    const a = sample(ps, r);
    const price = car.reference * LEVELS[a]!;
    const sold = r() < pSell(price, car.trueValue);
    return { car, action: a, propensity: ps[a]!, sold, reward: reward(price, car, sold, r) };
  });
}

/** Direct method: fit sale-rate per (level, value-bucket) from the log, then simulate. */
function fitDemand(log: LogRow[]) {
  const cells = new Map<string, { n: number; k: number }>();
  const bucket = (c: Car) => Math.min(3, Math.floor(c.reference / 200_000));
  for (const row of log) {
    const key = row.action + ':' + bucket(row.car);
    const c = cells.get(key) ?? { n: 0, k: 0 };
    c.n++; if (row.sold) c.k++; cells.set(key, c);
  }
  const overall = log.filter(r => r.sold).length / Math.max(1, log.length);
  return (car: Car, action: number) => {
    const c = cells.get(action + ':' + bucket(car));
    return c && c.n >= 5 ? c.k / c.n : overall;      // thin cells fall back, and that is the bias
  };
}

export function pricingScenario(): Scenario {
  return {
    id: 'pricing',
    account: 'Spinny',
    accountNote: 'Hypothesised from a used-car marketplace that takes inventory onto its own book and must price it.',
    archetype: 'no-truth',
    title: 'Used-car listing price',
    brief: 'Price a car the platform already owns. Too high and it sits, accruing holding cost. Too low and the margin is gone. There is no correct answer, only what happened at the price you chose.',
    whyThisMethod: 'No counterfactual is ever observed, so nothing can be graded. The estimate has to come from off-policy evaluation against a log the OLD policy generated, and that only works if the old policy explored.',
    scale: { volume: 12_000, valuePerDecisionInr: 26_000 },

    async run(adapter: Adapter, opts: RunOpts): Promise<ScenarioResult> {
      const cars = build(opts.n, opts.seed);
      const cache = new Cache(opts.cacheDir);
      const chosen = new Map<string, number>();
      let spent = 0, invalid = 0, failed = 0, done = 0;

      const SCHEMA = {
        type: 'object', additionalProperties: false,
        required: ['price_multiplier','rationale'],
        properties: {
          price_multiplier: { type: 'number', minimum: 0.85, maximum: 1.15,
            description: 'multiplier on the internal reference valuation' },
          rationale: { type: 'string' },
        },
      };
      const SYSTEM =
        'You price used cars that the platform has already purchased and is holding on its own books.\n\n' +
        'Holding costs run about Rs 420 a day, so a car that does not move inside thirty days erodes its own margin. ' +
        'Pricing below the market clearing level sells fast and gives away margin.\n' +
        'Return a multiplier on the internal reference valuation between 0.88 and 1.12.';

      for (const car of cars) {
        if (spent >= opts.maxUsd) break;
        const user = `${car.text}\nInternal reference valuation: Rs ${car.reference.toLocaleString('en-IN')}\nAcquired for: Rs ${car.acquisition.toLocaleString('en-IN')}`;
        const call = await callModel(adapter, cache, {
          scenario: 'pricing', system: SYSTEM, user,
          schema: SCHEMA as Record<string, unknown>, maxTokens: 300,
          mockTruth: { price_multiplier: Math.round((car.trueValue/car.reference)*100)/100, rationale: 'clearing level' },
        });
        spent += call.costUsd;
        const parsed: any = call.parsed;
        if (call.status === 'failed') failed++;
        if (call.status === 'ok' && parsed) {
          // snap to the nearest logged level so a propensity exists at all
          let bi = 0, bd = 9;
          for (let i = 0; i < LEVELS.length; i++) {
            const d = Math.abs(LEVELS[i]! - parsed.price_multiplier);
            if (d < bd) { bd = d; bi = i; }
          }
          chosen.set(car.id, bi);
        } else if (call.status === 'invalid') invalid++;
        done++; opts.onProgress?.(done, cars.length);
      }

      const scored = cars.filter(c => chosen.has(c.id));

      /** Evaluate the model's policy against a log, three ways, plus the truth. */
      function assess(temp: number, seed: number) {
        const log = makeLog(scored, temp, seed);
        const demand = fitDemand(log);
        const r2 = rng(seed + 77);

        let ipsNum = 0, ipsW = 0, direct = 0, dr = 0, clipped = 0;
        for (const row of log) {
          const a = chosen.get(row.car.id)!;
          const ps = logPropensities(row.car, temp);
          const pNew = a === row.action ? 1 : 0;                   // deterministic target policy
          const w = ps[row.action]! > 0 ? pNew / ps[row.action]! : 0;
          const wc = Math.min(w, 20);                              // clipping: bias for variance
          if (w > 20) clipped++;
          ipsNum += wc * row.reward; ipsW += wc;

          const priceNew = row.car.reference * LEVELS[a]!;
          const pS = demand(row.car, a);
          const dm = pS * (priceNew - row.car.acquisition - HOLD_COST_PER_DAY * 16)
                   + (1 - pS) * (-HOLD_COST_PER_DAY * WINDOW_DAYS);
          direct += dm;
          dr += dm + wc * (row.reward - (row.sold
                 ? (row.car.reference*LEVELS[row.action]! - row.car.acquisition - HOLD_COST_PER_DAY*16)
                 : -HOLD_COST_PER_DAY*WINDOW_DAYS));
        }
        const n = log.length || 1;

        // The truth, available only because this is a simulation.
        let truth = 0;
        for (const car of scored) {
          const a = chosen.get(car.id)!;
          const price = car.reference * LEVELS[a]!;
          const sold = r2() < pSell(price, car.trueValue);
          truth += reward(price, car, sold, r2);
        }
        return {
          temp,
          ips: ipsW > 0 ? ipsNum / n : NaN,
          snips: ipsW > 0 ? ipsNum / ipsW : NaN,
          direct: direct / n,
          doublyRobust: dr / n,
          truth: truth / scored.length,
          effectiveSample: ipsW > 0 ? (ipsW * ipsW) / log.reduce((a,row) => {
            const aa = chosen.get(row.car.id)!;
            const ps = logPropensities(row.car, temp);
            const w = ps[row.action]! > 0 ? Math.min((aa === row.action ? 1 : 0) / ps[row.action]!, 20) : 0;
            return a + w*w;
          }, 0) : 0,
          clipped, overlap: log.filter(row => chosen.get(row.car.id) === row.action).length / n,
        };
      }

      const exploring = assess(0.35, opts.seed + 1);      // a desk that randomised
      const deterministic = assess(0, opts.seed + 2);     // a desk that did not

      const V = 12_000;
      const value = exploring.truth * V;

      return {
        scenarioId: 'pricing', account: 'Spinny', archetype: 'no-truth',
        modelKey: adapter.spec.key, modelLabel: adapter.spec.label,
        valueInrPerMonth: value, baselineInrPerMonth: 0,
        headline: {
          label: 'Margin per car, doubly-robust estimate',
          value: `₹${Math.round(exploring.doublyRobust).toLocaleString('en-IN')}`,
          sub: `true ₹${Math.round(exploring.truth).toLocaleString('en-IN')} · estimate is ${Math.abs(exploring.doublyRobust-exploring.truth) < Math.abs(exploring.direct-exploring.truth) ? 'closer than' : 'worse than'} direct`,
        },
        detail: {
          n: scored.length, invalid, failed, levels: LEVELS,
          exploring, deterministic,
          errors: {
            direct: exploring.direct - exploring.truth,
            ips: exploring.ips - exploring.truth,
            snips: exploring.snips - exploring.truth,
            doublyRobust: exploring.doublyRobust - exploring.truth,
          },
          collapse: {
            overlapExploring: exploring.overlap,
            overlapDeterministic: deterministic.overlap,
            essExploring: exploring.effectiveSample,
            essDeterministic: deterministic.effectiveSample,
          },
        },
        caveats: [
          'The market is simulated, so the true policy value is knowable here and the estimators can be scored against it. That is the only reason this panel can show which estimator was closest; on real data you would never find out.',
          'The target policy is deterministic, which is the honest hard case for importance weighting and the reason the effective sample size falls so far below the row count.',
          'The deterministic-log column is the finding: with no exploration in the history, every propensity is one or zero and no amount of data answers the question.',
        ],
        costUsd: spent, attempts: done,
      };
    },
  };
}
