/**
 * Three ways to ask a model how sure it is, measured against each other on the
 * same items. They are not interchangeable and the differences are the point.
 *
 *  SELF-REPORT — ask it for a number. Free, universally available, and the
 *  weakest of the three. Models are trained to sound helpful, and a number
 *  produced by the same forward pass that produced the answer is generated by
 *  the same process that was wrong. It is also coarse: models emit a handful of
 *  values (0.8, 0.9, 0.95, 0.99), which caps how finely you can threshold.
 *
 *  SAMPLING AGREEMENT — ask k times at temperature, count how often it lands on
 *  the same answer. Costs k times as much and is usually worth it: it measures
 *  something about the model's actual distribution rather than its opinion of
 *  itself, and it works on every provider. Its weakness is confident
 *  consistency — a model reliably wrong the same way scores maximum agreement.
 *
 *  MEAN LOGPROB — the model's own token probabilities. Closest to a real
 *  internal signal, but only some providers expose it, and it is contaminated
 *  by the answer's shape: long or rare-token answers score lower for reasons
 *  that have nothing to do with correctness.
 *
 * The bench computes whichever are available per model and reports AURC for
 * each separately, so the choice of confidence source is a measured decision
 * rather than an assumption. On most workloads the ranking is not what you would
 * expect from the price of collecting them.
 */

import type { ConfidenceSource } from '../types.ts';

/** Canonical form of an answer, so agreement is about substance not formatting. */
export function canonicalAnswer(parsed: unknown): string {
  if (parsed === null || typeof parsed !== 'object') return JSON.stringify(parsed);
  const strip = (v: unknown): unknown => {
    if (Array.isArray(v)) return v.map(strip);
    if (v && typeof v === 'object') {
      const o = v as Record<string, unknown>;
      return Object.keys(o).filter((k) => k !== 'confidence').sort()
        .reduce<Record<string, unknown>>((acc, k) => { acc[k] = strip(o[k]); return acc; }, {});
    }
    if (typeof v === 'string') return v.toLowerCase().trim();
    return v;
  };
  return JSON.stringify(strip(parsed));
}

export function selfReport(parsed: unknown): number | null {
  if (!parsed || typeof parsed !== 'object') return null;
  const c = (parsed as Record<string, unknown>).confidence;
  return typeof c === 'number' && Number.isFinite(c) ? Math.min(1, Math.max(0, c)) : null;
}

/** Share of samples matching the modal answer. Needs k >= 2 to mean anything. */
export function samplingAgreement(parsedSamples: unknown[]): number | null {
  const valid = parsedSamples.filter((p) => p !== null);
  if (valid.length < 2) return null;
  const counts = new Map<string, number>();
  for (const p of valid) {
    const k = canonicalAnswer(p);
    counts.set(k, (counts.get(k) ?? 0) + 1);
  }
  return Math.max(...counts.values()) / valid.length;
}

/**
 * Geometric mean per-token probability. Not a probability of correctness, and
 * treated as an ordinal score only — isotonic recalibration maps it onto one.
 */
export function fromLogprob(meanLogprob: number | null): number | null {
  if (meanLogprob === null || !Number.isFinite(meanLogprob)) return null;
  return Math.min(1, Math.max(0, Math.exp(meanLogprob)));
}

export const SOURCES: ConfidenceSource[] = ['self_report', 'sampling_agreement', 'mean_logprob'];
