/**
 * SCENARIOS — the unit of this bench, and the whole argument in one file.
 *
 * A benchmark assumes one shape: an item, an answer, a label, a score. That
 * shape fits exactly one of the four business archetypes below, and applying it
 * to the other three does not produce a worse number. It produces a confident
 * number about the wrong quantity.
 *
 *   A · VOLUME GRIND        Meesho catalogue enrichment
 *       Unit of evaluation: THE ITEM.
 *       Millions of cheap decisions. Cost per resolved unit is the game, and
 *       item-level grading works exactly as advertised.
 *
 *   B · HIGH-STAKES CALL    Aye Finance MSME underwriting
 *       Unit of evaluation: THE COHORT.
 *       You never learn whether one decision was right. You learn, eighteen
 *       months later, what a portfolio of them did. So there is no per-item
 *       label to grade against and accuracy is not the objective: expected
 *       profit per application is, and it is driven by an asymmetry where one
 *       bad approval costs the principal and one bad decline costs the margin.
 *
 *   C · NO GROUND TRUTH     Spinny used-car pricing
 *       Unit of evaluation: THE POLICY.
 *       There is no correct price. There is only what happened at the price you
 *       chose, and you cannot observe what would have happened at any other.
 *       Worse: your history was generated by your OLD policy, so a naive replay
 *       of a new one is biased by the very thing you are trying to change. This
 *       needs off-policy evaluation, not grading.
 *
 *   D · ADVERSARIAL/ACTING  Cred collections
 *       Unit of evaluation: THE TRAJECTORY.
 *       The counterparty responds to what you did, so every action changes the
 *       distribution of the next state. A static test set is a photograph of a
 *       conversation that never happened.
 *
 * Each archetype therefore ships its own evaluator. They share cost accounting,
 * statistics and reporting, and share nothing about what "correct" means.
 */

import type { Adapter } from '../types.ts';

export type Archetype = 'volume' | 'stakes' | 'no-truth' | 'adversarial';

export const ARCHETYPE_META: Record<Archetype, {
  label: string; unit: string; method: string; gradeable: boolean; note: string;
}> = {
  volume: {
    label: 'Volume grind', unit: 'the item',
    method: 'item-level grading', gradeable: true,
    note: 'A right answer exists for every item, and you can check it the same day.',
  },
  stakes: {
    label: 'High-stakes single call', unit: 'the cohort',
    method: 'delayed-label cohort backtest', gradeable: false,
    note: 'You never learn what happened to the ones you declined, so there is no answer key.',
  },
  'no-truth': {
    label: 'No ground truth', unit: 'the policy',
    method: 'off-policy evaluation with propensity correction', gradeable: false,
    note: 'There is no right price. Only what happened at the one you set, and nothing about the rest.',
  },
  adversarial: {
    label: 'Adversarial or acting', unit: 'the trajectory',
    method: 'adversarial rollout over a horizon', gradeable: false,
    note: 'Your own actions create next week\u2019s states, so a fixed test set is one path through a tree.',
  },
};

/** What every archetype must produce, so four incomparable methods can share one map. */
export type ScenarioResult = {
  scenarioId: string;
  account: string;
  archetype: Archetype;
  modelKey: string;
  modelLabel: string;

  /**
   * The single number a founder compares across accounts: rupees of business
   * value per month, net of every cost the system introduces. It is the ONLY
   * quantity that means the same thing in all four archetypes, which is why the
   * map is denominated in it rather than in accuracy.
   */
  valueInrPerMonth: number;
  baselineInrPerMonth: number;

  /** Archetype-native headline. Deliberately NOT comparable across archetypes. */
  headline: { label: string; value: string; sub?: string };

  /** Whatever this archetype's method produces, for its own panel. */
  detail: Record<string, unknown>;

  /** Honest limits specific to this evaluation, surfaced on the page. */
  caveats: string[];

  costUsd: number;
  attempts: number;
};

export type Scenario = {
  id: string;
  account: string;
  accountNote: string;
  archetype: Archetype;
  title: string;
  /** The problem as the company would state it. */
  brief: string;
  /** Why the standard toolkit does or does not apply here. */
  whyThisMethod: string;
  /** Monthly volume of decisions, and what one decision is worth. */
  scale: { volume: number; valuePerDecisionInr: number };
  run: (adapter: Adapter, opts: RunOpts) => Promise<ScenarioResult>;
};

export type RunOpts = {
  n: number;
  seed: number;
  cacheDir: string;
  maxUsd: number;
  onProgress?: (done: number, total: number) => void;
};

/**
 * HYPOTHESISED ACCOUNTS.
 *
 * Every account below is reasoned from a publicly known business model to the
 * AI problem that model must therefore create. Nothing here is a claim about
 * any company's actual systems, roadmap, vendors or internal performance, and
 * no figure is represented as theirs. They are here because naming a real
 * business makes the archetype legible, and an archetype nobody recognises
 * teaches nothing.
 */
export const ACCOUNT_DISCLAIMER =
  'Accounts are hypothesised from public business models. Nothing here is a claim about any company’s actual systems, vendors, roadmap or performance, and no figure shown is theirs.';
